services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 30

  mock-api:
    build: ./mock_api
    container_name: mock-api
    environment:
      API_KEY: ${API_KEY:?API_KEY must be set}
      API_RATE_LIMIT_PER_MIN: ${API_RATE_LIMIT_PER_MIN:-300}
      TZ: ${TZ:-UTC}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  airflow:
    build: ./airflow
    image: airflow-local
    container_name: airflow
    working_dir: /workspace
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DBT_PROFILES_DIR: /opt/airflow/.dbt
      TZ: ${TZ:-UTC}
      AIRFLOW_CONN_POSTGRES_DEFAULT: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      API_BASE_URL: http://mock-api:8000
      API_KEY: ${API_KEY:?API_KEY must be set}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    entrypoint: ["/bin/bash"]
    command:
      - -lc
      - |
          set -euo pipefail

          airflow db init
          airflow users create --role Admin --username admin --password admin --firstname Admin --lastname User --email admin@example.com || true
          airflow connections delete postgres_default || true
          airflow connections add postgres_default --conn-uri "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

          airflow webserver &
          exec airflow scheduler
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./dbt:/usr/app
      - ./dbt/profiles:/opt/airflow/.dbt
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      mock-api:
        condition: service_healthy

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.latest
    container_name: dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: /root/.dbt
      TZ: ${TZ:-UTC}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dbt:/usr/app
      - ./dbt/profiles:/root/.dbt
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-lc", "dbt deps && dbt run && tail -f /dev/null"]

volumes:
  pgdata: 

networks:
  default:
    external:
      name: de-master
